'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1022
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property PayPeriodLength() As Integer
            Get
                Return CType(Me("PayPeriodLength"),Integer)
            End Get
            Set
                Me("PayPeriodLength") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2016-12-19")>  _
        Public Property PayPeriodStartDate() As Date
            Get
                Return CType(Me("PayPeriodStartDate"),Date)
            End Get
            Set
                Me("PayPeriodStartDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11.00")>  _
        Public Property PayRate() As Decimal
            Get
                Return CType(Me("PayRate"),Decimal)
            End Get
            Set
                Me("PayRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MondayIsDayOff() As Boolean
            Get
                Return CType(Me("MondayIsDayOff"),Boolean)
            End Get
            Set
                Me("MondayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MondayHours() As Decimal
            Get
                Return CType(Me("MondayHours"),Decimal)
            End Get
            Set
                Me("MondayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MondayMinutes() As Decimal
            Get
                Return CType(Me("MondayMinutes"),Decimal)
            End Get
            Set
                Me("MondayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MondayLunchBreak() As Decimal
            Get
                Return CType(Me("MondayLunchBreak"),Decimal)
            End Get
            Set
                Me("MondayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TuesdayIsDayOff() As Boolean
            Get
                Return CType(Me("TuesdayIsDayOff"),Boolean)
            End Get
            Set
                Me("TuesdayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TuesdayHours() As Decimal
            Get
                Return CType(Me("TuesdayHours"),Decimal)
            End Get
            Set
                Me("TuesdayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TuesdayMinutes() As Decimal
            Get
                Return CType(Me("TuesdayMinutes"),Decimal)
            End Get
            Set
                Me("TuesdayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TuesdayLunchBreak() As Decimal
            Get
                Return CType(Me("TuesdayLunchBreak"),Decimal)
            End Get
            Set
                Me("TuesdayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WednesdayIsDayOff() As Boolean
            Get
                Return CType(Me("WednesdayIsDayOff"),Boolean)
            End Get
            Set
                Me("WednesdayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WednesdayHours() As Decimal
            Get
                Return CType(Me("WednesdayHours"),Decimal)
            End Get
            Set
                Me("WednesdayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WednesdayMinutes() As Decimal
            Get
                Return CType(Me("WednesdayMinutes"),Decimal)
            End Get
            Set
                Me("WednesdayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WednesdayLunchBreak() As Decimal
            Get
                Return CType(Me("WednesdayLunchBreak"),Decimal)
            End Get
            Set
                Me("WednesdayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ThursdayIsDayOff() As Boolean
            Get
                Return CType(Me("ThursdayIsDayOff"),Boolean)
            End Get
            Set
                Me("ThursdayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ThursdayHours() As Decimal
            Get
                Return CType(Me("ThursdayHours"),Decimal)
            End Get
            Set
                Me("ThursdayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ThursdayMinutes() As Decimal
            Get
                Return CType(Me("ThursdayMinutes"),Decimal)
            End Get
            Set
                Me("ThursdayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ThursdayLunchBreak() As Decimal
            Get
                Return CType(Me("ThursdayLunchBreak"),Decimal)
            End Get
            Set
                Me("ThursdayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FridayIsDayOff() As Boolean
            Get
                Return CType(Me("FridayIsDayOff"),Boolean)
            End Get
            Set
                Me("FridayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FridayHours() As Decimal
            Get
                Return CType(Me("FridayHours"),Decimal)
            End Get
            Set
                Me("FridayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FridayMinutes() As Decimal
            Get
                Return CType(Me("FridayMinutes"),Decimal)
            End Get
            Set
                Me("FridayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FridayLunchBreak() As Decimal
            Get
                Return CType(Me("FridayLunchBreak"),Decimal)
            End Get
            Set
                Me("FridayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SaturdayIsDayOff() As Boolean
            Get
                Return CType(Me("SaturdayIsDayOff"),Boolean)
            End Get
            Set
                Me("SaturdayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SaturdayHours() As Decimal
            Get
                Return CType(Me("SaturdayHours"),Decimal)
            End Get
            Set
                Me("SaturdayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SaturdayMinutes() As Decimal
            Get
                Return CType(Me("SaturdayMinutes"),Decimal)
            End Get
            Set
                Me("SaturdayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SaturdayLunchBreak() As Decimal
            Get
                Return CType(Me("SaturdayLunchBreak"),Decimal)
            End Get
            Set
                Me("SaturdayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SundayIsDayOff() As Boolean
            Get
                Return CType(Me("SundayIsDayOff"),Boolean)
            End Get
            Set
                Me("SundayIsDayOff") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SundayHours() As Decimal
            Get
                Return CType(Me("SundayHours"),Decimal)
            End Get
            Set
                Me("SundayHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SundayMinutes() As Decimal
            Get
                Return CType(Me("SundayMinutes"),Decimal)
            End Get
            Set
                Me("SundayMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SundayLunchBreak() As Decimal
            Get
                Return CType(Me("SundayLunchBreak"),Decimal)
            End Get
            Set
                Me("SundayLunchBreak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enter a withholding name ...")>  _
        Public Property AdditionalWithholdingName1() As String
            Get
                Return CType(Me("AdditionalWithholdingName1"),String)
            End Get
            Set
                Me("AdditionalWithholdingName1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00")>  _
        Public Property AdditionalWithholdingValue1() As Decimal
            Get
                Return CType(Me("AdditionalWithholdingValue1"),Decimal)
            End Get
            Set
                Me("AdditionalWithholdingValue1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enter a withholding name ...")>  _
        Public Property AdditionalWithholdingName2() As String
            Get
                Return CType(Me("AdditionalWithholdingName2"),String)
            End Get
            Set
                Me("AdditionalWithholdingName2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00")>  _
        Public Property AdditionalWithholdingValue2() As Decimal
            Get
                Return CType(Me("AdditionalWithholdingValue2"),Decimal)
            End Get
            Set
                Me("AdditionalWithholdingValue2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Friday")>  _
        Public Property PayDay() As String
            Get
                Return CType(Me("PayDay"),String)
            End Get
            Set
                Me("PayDay") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\PaycheckEstimatorDB.sdf")>  _
        Public ReadOnly Property PaycheckEstimatorDBConnectionString() As String
            Get
                Return CType(Me("PaycheckEstimatorDBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\PaycheckEstimatorDB.mdf"& _ 
            ";Integrated Security=True;User Instance=True")>  _
        Public ReadOnly Property PaycheckEstimatorDBConnectionString1() As String
            Get
                Return CType(Me("PaycheckEstimatorDBConnectionString1"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Paycheck_Esitmator.My.MySettings
            Get
                Return Global.Paycheck_Esitmator.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
